# Generated by Django 4.1.1 on 2022-09-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('icon', models.TextField(help_text='path tag of svg icon', verbose_name='Icon path tag')),
                ('content', models.TextField(verbose_name='Content')),
                ('addition', models.TextField(verbose_name='Additional Content')),
            ],
        ),
    ]
