# Generated by Django 4.1.1 on 2022-09-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_rename_info_about_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/', verbose_name='Avatar')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('location', models.CharField(help_text='Specify only city, thus way it looks better', max_length=60, verbose_name='Location')),
            ],
        ),
    ]
