# Generated by Django 4.1.1 on 2022-09-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='avatar',
            new_name='image',
        ),
    ]
