# Generated by Django 4.1.1 on 2022-09-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stackitem',
            options={'verbose_name': 'Stack Item', 'verbose_name_plural': 'Stack Items'},
        ),
        migrations.AddField(
            model_name='project',
            name='actual_link',
            field=models.URLField(blank=True, null=True, verbose_name='Project Link'),
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(default=1, verbose_name='Github Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='temp_link',
            field=models.URLField(blank=True, help_text='Some test hosting like vercel, etc...', null=True, verbose_name='Temporary project link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='In US dollars', max_digits=6, verbose_name='Budget'),
        ),
    ]
